version: '3'

services:
  mlflow:
    build: mlflow/
    ports:
      - "8001:5000"
    volumes:
      - "~/mlflow:/mlflow"
    restart: always
    environment:
      BACKEND_URI: sqlite:////mlflow/backend/mlflow.sqlite
      ARTIFACT_ROOT: /mlflow/artifacts

  dagster:
    build: dagster/
    ports:
      - "8000:5000"
    volumes:
      - "~/dagster:/dagster"
      - "~/app:/app"
    restart: always
    environment:
      DAGSTER_HOME: /dagster