version: '3'

services:
  mlflow:
    build: mlflow/
    image: mlflow
    ports:
      - "8001:5000"
    volumes:
      - "~/mlflow:/mlflow"
    restart: always
    environment:
      BACKEND_URI: sqlite:////mlflow/backend/mlflow.sqlite
      ARTIFACT_ROOT: /mlflow/artifacts
    networks:
      mynetwork:
        ipv4_address: 172.20.0.10

  dagster:
    build: dagster/
    image: dagster
    ports:
      - "8000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "~/dagster:/dagster"
      - "~/app:/app"
    restart: always
    environment:
      DAGSTER_HOME: /dagster
    networks:
      mynetwork:
        ipv4_address: 172.20.0.11

  bridge:
    image: 'quay.io/domino/bridge:latest'
    ports:
      - '9000:3000'
    environment:
      - BRIDGE_DEPLOY_KIND=localhost
      - BRIDGE_MLFLOW_URI=http://172.20.0.10:8001/
    depends_on:
      - mlflow

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24
