load_from:
  - python_file:
      working_directory: ../app/dev/pipelines/
      relative_path: ../app/dev/pipelines/repos.py
      location_name: dev
  - python_file:
      working_directory: ../app/staging/pipelines/
      relative_path: ../app/dev/pipelines/repos.py
      location_name: staging
  - python_file:
      working_directory: ../app/prod/pipelines/
      relative_path: ../app/dev/pipelines/repos.py
      location_name: prod
